spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.92.167.193:3306/ssm1
    username: root
    password: 118647
    hikari.max-lifetime: 30000
    thymeleaf:
      prefix: classpath:/templates/
hadoop:
  name-node: hdfs://49.232.221.239:9000
  namespace: /user


